// <auto-generated />
using Alphabyte_Technology_Ltd_.DbConn;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alphabyte_Technology_Ltd_.Migrations
{
    [DbContext(typeof(DbConnectionClass))]
    partial class DbConnectionClassModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Alphabyte_Technology_Ltd_.Models.Department", b =>
                {
                    b.Property<int>("Dept_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Dept_Id"), 1L, 1);

                    b.Property<int>("Department_DivisionId")
                        .HasColumnType("int");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Dept_Id");

                    b.HasIndex("Department_DivisionId");

                    b.ToTable("DepartmentTable");

                    b.HasData(
                        new
                        {
                            Dept_Id = 1,
                            Department_DivisionId = 1,
                            DeptName = "CSE"
                        },
                        new
                        {
                            Dept_Id = 2,
                            Department_DivisionId = 1,
                            DeptName = "SE"
                        },
                        new
                        {
                            Dept_Id = 3,
                            Department_DivisionId = 2,
                            DeptName = "MGT"
                        },
                        new
                        {
                            Dept_Id = 4,
                            Department_DivisionId = 2,
                            DeptName = "THM"
                        },
                        new
                        {
                            Dept_Id = 5,
                            Department_DivisionId = 1,
                            DeptName = "Software"
                        });
                });

            modelBuilder.Entity("Alphabyte_Technology_Ltd_.Models.Division", b =>
                {
                    b.Property<int>("DivisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DivisionId"), 1L, 1);

                    b.Property<string>("DivisionName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("DivisionId");

                    b.ToTable("DivisionTable");

                    b.HasData(
                        new
                        {
                            DivisionId = 1,
                            DivisionName = "IT"
                        },
                        new
                        {
                            DivisionId = 2,
                            DivisionName = "BBA"
                        });
                });

            modelBuilder.Entity("Alphabyte_Technology_Ltd_.Models.InterViewerDetails", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("DoB")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("InterViewerDetails_DepartmentDept_Id")
                        .HasColumnType("int");

                    b.Property<int>("InterViewerDetails_DivisionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ResumeFile")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("InterViewerDetails_DepartmentDept_Id");

                    b.HasIndex("InterViewerDetails_DivisionId");

                    b.ToTable("InterViewerDetailsTable");

                    b.HasData(
                        new
                        {
                            Id = "10000001",
                            DoB = "2000-09-07",
                            InterViewerDetails_DepartmentDept_Id = 5,
                            InterViewerDetails_DivisionId = 1,
                            Name = "Ashraful Alam",
                            ResumeFile = "File1.pdf"
                        },
                        new
                        {
                            Id = "10000002",
                            DoB = "1998-04-21",
                            InterViewerDetails_DepartmentDept_Id = 1,
                            InterViewerDetails_DivisionId = 1,
                            Name = "M.A. Monaem Khan",
                            ResumeFile = "File2.pdf"
                        });
                });

            modelBuilder.Entity("Alphabyte_Technology_Ltd_.Models.Department", b =>
                {
                    b.HasOne("Alphabyte_Technology_Ltd_.Models.Division", "Department_Division")
                        .WithMany()
                        .HasForeignKey("Department_DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department_Division");
                });

            modelBuilder.Entity("Alphabyte_Technology_Ltd_.Models.InterViewerDetails", b =>
                {
                    b.HasOne("Alphabyte_Technology_Ltd_.Models.Department", "InterViewerDetails_Department")
                        .WithMany()
                        .HasForeignKey("InterViewerDetails_DepartmentDept_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alphabyte_Technology_Ltd_.Models.Division", "InterViewerDetails_Division")
                        .WithMany()
                        .HasForeignKey("InterViewerDetails_DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterViewerDetails_Department");

                    b.Navigation("InterViewerDetails_Division");
                });
#pragma warning restore 612, 618
        }
    }
}
